[[collection]]
group = "english"
name = "NSG English"

[[collection.insert]]
id = "corp_basic_actions"
title = "Corp Basic Actions"
insert_groups = ["Basic Actions"]

[[collection.insert]]
id = "mark_archives"
title = "Mark Archives"
insert_groups = ["Mark Cards"]

[[collection.insert]]
id = "mark_hq"
title = "Mark HQ"
insert_groups = ["Mark Cards"]

[[collection.insert]]
id = "mark_rnd"
title = "Mark R&D"
insert_groups = ["Mark Cards"]

[[collection.insert]]
id = "runner_basic_actions"
title = "Runner Basic Actions"
insert_groups = ["Basic Actions"]

[[collection.insert]]
id = "tag_tracking_area"
title = "Tag Tracking Area"

[[collection.insert]]
id = "turn_structure_runner"
title = "Turn Structure: Runner"
insert_groups = ["Turn Structure"]

[[collection.insert]]
id = "turn_structure_corp"
title = "Turn Structure: Corp"
insert_groups = ["Turn Structure"]

[[collection.printing]]
spec = "system_gateway"
name = "System Gateway (English)"

[[collection.printing]]
spec = "elevation"
name = "Elevation (English)"

[[collection.printing]]
spec = "downfall"
name = "Downfall (English)"

[[collection.printing]]
spec = "uprising"
name = "Uprising (English)"

[[collection.printing]]
spec = "midnight_sun"
name = "Midnight Sun (English)"

[[collection.printing]]
spec = "parhelion"
name = "Parhelion (English)"

[[collection.printing]]
spec = "the_automata_initiative"
name = "The Automata Initiative (English)"

[[collection.printing]]
spec = "rebellion_without_rehearsal"
name = "Rebellion Without Rehearsal (English)"

[[card]]
id = "corsair"
title = "Corsair"
group = "english"
printing_id = 36004
printing_name = "Vantage Point (English)"

[[card]]
id = "lampades"
title = "Lampades"
group = "english"
printing_id = 36005
printing_name = "Vantage Point (English)"

[[card]]
id = "underdome_irregulars"
title = "Underdome Irregulars"
group = "english"
printing_id = 36016
printing_name = "Vantage Point (English)"

[[card]]
id = "synchrocyclotron"
title = "Synchrocyclotron"
group = "english"
printing_id = 36027
printing_name = "Vantage Point (English)"

[[card]]
id = "flood_the_market"
title = "Flood the Market"
group = "english"
printing_id = 36053
printing_name = "Vantage Point (English)"

[[card]]
id = "melies_u_only_the_brightest"
title = "Méliès U: Only The Brightest"
faces = [
    "Tenure Floors: Méliès U",
    "Subsurface Labs: Méliès U",
    "Disposal Grounds: Méliès U",
]
group = "english"
printing_id = 36036
printing_name = "Vantage Point (English)"

[[card]]
id = "virtual_intelligence_pi_you_can_call_me_vic"
title = "Virtual Intelligence, P.I.: “You Can Call Me Vic”"
stripped_title = "Virtual Intelligence, P.I.: \"You Can Call Me Vic\""
group = "english"
printing_id = 36009
printing_name = "Vantage Point (English)"

[[card]]
id = "editorial_division_ad_nihilum"
title = "Editorial Division: Ad Nihilum"
group = "english"
printing_id = 36046
printing_name = "Vantage Point (English)"

[[card]]
id = "nihilo_agent"
title = "Nihilo Agent"
group = "english"
printing_id = 36049
printing_name = "Vantage Point (English)"

[[card]]
id = "vulture_fund"
title = "Vulture Fund"
group = "english"
printing_id = 36063
printing_name = "Vantage Point (English)"

[[card]]
id = "hiram_0mission_svensson_shadow_of_the_past"
title = "Hiram “0mission” Svensson: Shadow of the Past"
stripped_title = "Hiram \"0mission\" Svensson: Shadow of the Past"
group = "english"
printing_id = 36017
printing_name = "Vantage Point (English)"

[[card]]
id = "let_them_dream"
title = "Let Them Dream"
group = "english"
printing_id = 36066
printing_name = "Vantage Point (English)"

[[card]]
id = "melies_city_luxury_line"
title = "Méliès City Luxury Line"
stripped_title = "Melies City Luxury Line"
group = "english"
printing_id = 36026
printing_name = "Vantage Point (English)"

[[card]]
id = "stick_and_poke"
title = "Stick and Poke"
group = "english"
printing_id = 36008
printing_name = "Vantage Point (English)"

[[card]]
id = "flagship"
title = "Flagship"
group = "english"
printing_id = 36064
printing_name = "Vantage Point (English)"

[[card]]
id = "magistrate_revontulet"
title = "Magistrate Revontulet"
group = "english"
printing_id = 36048
printing_name = "Vantage Point (English)"

[[nrdb_remap]]
from = 32001
to = 33009

[[nrdb_remap]]
from = 32002
to = 33018

[[nrdb_remap]]
from = 32003
to = 33022

[[nrdb_remap]]
from = 32004
to = 33036

[[nrdb_remap]]
from = 32005
to = 33043

[[nrdb_remap]]
from = 32006
to = 33056

[[nrdb_remap]]
from = 32007
to = 33058

[[nrdb_remap]]
from = 27001
to = 26072

[[nrdb_remap]]
from = 27002
to = 26078

[[nrdb_remap]]
from = 27003
to = 26091

[[nrdb_remap]]
from = 27004
to = 26096

[[nrdb_remap]]
from = 27005
to = 26112

[[nrdb_remap]]
from = 27006
to = 26117

[[nrdb_remap]]
from = 27007
to = 26127

[[nrdb_remap]]
from = 1110
to = 30075

[[nrdb_remap]]
from = 20132
to = 30075

[[nrdb_remap]]
from = 25146
to = 30075

[[nrdb_remap]]
from = 1050
to = 30030

[[nrdb_remap]]
from = 20056
to = 30030

[[nrdb_remap]]
from = 25059
to = 30030

[[nrdb_remap]]
from = 3009
to = 26099

[[nrdb_remap]]
from = 13048
to = 26124

[[nrdb_remap]]
from = 2080
to = 26129

[[nrdb_remap]]
from = 20124
to = 26129

[[nrdb_remap]]
from = 3046
to = 26090

[[nrdb_remap]]
from = 3053
to = 26094
